### ISSUE TITLE
Heroku App is broken :(

### ISSUE THREAD

**Issue by Zuljita** [brian-thomas/df-treasure-generator-service#2]
For whatever reason, the live version of this on Heroku is broken.  It has been a phenomenal resource to the GURPS community, I hope it can be fixed.

**Comment by brian-thomas** [comment]
Logs are unclear about what is happening. I've restarted it and it appears to work. Please notify me again if you find it crashing. Not sure why its doing this, last update was back in March 2020 and its been fine for months...
